subscription_id         = "ecc74148-1a84-4ec7-99bb-d26aba7f9c0d"
resource_group_name     = "rg-tf-poc"
storage_account_name    = "sadeiaf5exwvmh1bx"
container_name          = "tfstate"
key                     = "terraform.tfstate"