subscription_id         = "ecc74148-1a84-4ec7-99bb-d26aba7f9c0d"
resource_group_name     = "rg-poc-tf-permissions-uksouth"
storage_account_name    = "satfhd892i3h489"
container_name          = "tfstate"
key                     = "terraform.tfstate"