subscription_id         = "ecc74148-1a84-4ec7-99bb-d26aba7f9c0d"
resource_group_name     = "rg-tf-proof-of-concepts-management-poc-uksouth"
storage_account_name    = "salb7yiqzdooe8r90"
container_name          = "tfstate"
key                     = "terraform.tfstate"